### ISSUE TITLE
Should I get Zenhub?

### ISSUE THREAD

**Issue by CoreyBenefiel** [CoreyBenefiel/hello-world#12]
Ask Dee and Jenny?

**Comment by jennybeaumont** [comment]
You would gain access to Zenhub via the HM org licence - not all projects use it (that is, we don't always have a choice of which tool we use). NewsPress, for example, uses native GitHub Projects to manage the backlog and sprints (we'll run you through, no worries :)).

**Comment by thewebprincess** [comment]
No need to access it until you need it, none of the in house projects use it currently. If/when you do need it we'll add you an with the org license as Jenny suggests.
