### ISSUE TITLE
Github education

### ISSUE THREAD

**Issue by CoreyBenefiel** [CoreyBenefiel/hello-world#2]
Gain intermediate level understanding of Github

**Comment by thewebprincess** [comment]
This project is a great initiative in getting to know github as an issue tracker and kan ban board for tracking progress. 

The other element of github that's critical to your dev team its primary function in that  it tracks revisions in the code base.

You can read a brief overview of that here https://medium.com/crowdbotics/a-dead-simple-intro-to-github-for-the-non-technical-f9d56410a856
