### ISSUE TITLE
Forecast education

### ISSUE THREAD

**Issue by CoreyBenefiel** [CoreyBenefiel/hello-world#4]
Get familiar with Forecast. Ask John if Harvest is also used at HM?

**Comment by jennybeaumont** [comment]
My name is not John, but we do not use Harvest :) you'll get a full briefing on our forecasting and timetracking systems.

**Comment by thewebprincess** [comment]
@petyaraykovska will give you the full rundown of the allocation, and time tracking tools we use this week.

**Comment by petyaraykovska** [comment]
If you'd like to read a bit about how we use Forecast beforehand, I've created your account today so you can log in and the docs on Forecast are here:

https://client-services-handbook.hmn.md/the-project/resourcing/allocation-tools/harvest-forecast/
