### ISSUE TITLE
Access to HM site

### ISSUE THREAD

**Issue by CoreyBenefiel** [CoreyBenefiel/hello-world#5]
Ask John about access to HM site to read links etc from Slack.

**Comment by petyaraykovska** [comment]
John's going to give you access to:

- [ ]  Engineering Handbook
- [ ]  Updates
- [ ]  Announcements
- [ ]  Handbook (note that while most of the Employee handbook is public, there are internal pages only visible to logged in users)
- [ ]  Client services
- [ ]  Project managers
- [ ]  Client services handbook . -WIP

You can check these off once you get access to them ;)
