### ISSUE TITLE
Hangouts. Which ones?

### ISSUE THREAD

**Issue by CoreyBenefiel** [CoreyBenefiel/hello-world#8]
Which hangouts should I attend? Have received PM invites but also Americas general as well. Ask Dee.

**Comment by petyaraykovska** [comment]
I'll also invite you to the Allocation Calls so you get a sense of what that's like. As a PM I think you should attend these calls:

- Your project calls - vary per project 
- Client Services EMEA weekly call (as this is the region your project operates in, there's one Client Services call for each region) - will check if you've been invited and invite you if not
- Allocation Sync call - optional but recommended call for project managers (only strictly required if you're also serving as an allocation representative for the region. As a PM it's only recommended that you attend and it's good to attend if you have an open allocation issue for your project at the moment) - I will invite you to the one for EMEA

Other calls I'm missing? @thewebprincess

**Comment by thewebprincess** [comment]
The PM hangout, which you mentioned, you've been invited to both the EMEA, and Americas one, but only need to attend one of them - I think you're marked as optional in the US hangout. Though I'm not sure if by Americas general hangout you mean their Friday afternoon  social? if so, again, optional.
