### ISSUE TITLE
NewsPress Scrum Rhythm

### ISSUE THREAD

**Issue by CoreyBenefiel** [CoreyBenefiel/hello-world#9]
Pick Jenny's brain in detail regarding the scrum ceremonies she has in place, frequecny, how she runs them and documents them.

Aim is to learn broadly how it's done is HM, and exactly how it's done in the NewsPress project. Objective is to take up the NewsPress project with no impact on the team or client.

**Comment by jennybeaumont** [comment]
You will soon have access to the project p2 (our internal documentation platform), and can see a post I prepared which details this https://newsuk.hmn.md/2019/11/11/preparing-to-hand-over-newspress/

Quickly:

* NewsPress runs 2 week sprints, running M-F
* Internal Daily standups dev team only
* Periodic cross team standups as needed
* Weekly cross agency call
* Biweekly sprint review with client + stakeholders
* Biweekly internal sprint retro
* Weekly PO refinement (Dan is the project's PO)
* Weekly team refinement

**Comment by jennybeaumont** [comment]
Also, I will be updating this in the coming week, but if you want to get a jump start on the project, you can dig into this onboarding doc https://docs.google.com/document/d/1MNoNsFf23AhvhmroSuGJFc14eaHXztyBpozToNmMows/edit#

You should be able to access it with your HM Gmail account.

**Comment by CoreyBenefiel** [comment]
Thanks Jenny,

That's all very helpful! Will dive into it tomorrow.
